"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var archivos = require('fs/promises');
var lmdb_1 = require("./lmdb");
var movie_1 = require("./movie");
var profesional_1 = require("./profesional");
var a = new profesional_1.profesional("sergio Arroyo", 35, 100, 1.65, true, "Inglaterra", 3, "director");
var b = new profesional_1.profesional("Irene rubio", 31, 90, 1.70, false, "España", 0, "escritor");
var c = new profesional_1.profesional("juan pepe", 49, 105, 1.65, true, "España", 3, "actor");
var d = new profesional_1.profesional("benito", 49, 105, 1.65, false, "Francia", 3, "actor");
var pelicula1 = new movie_1.movie("Piratas del caribe", 10, "Ingles", "aventura");
var pelicula2 = new movie_1.movie("Titanic", 25, "España", "comedia");
pelicula1.director = a;
pelicula1.writer = b;
pelicula1.actors = [c, d];
pelicula2.director = a;
pelicula2.writer = b;
pelicula2.actors = [c, d];
var array = [pelicula1, pelicula2];
var datos = new lmdb_1.lmdb(array);
var imprimir = JSON.stringify(datos);
archivos.writeFile("lmdbb.json", imprimir);
